from modules.word_controller import *

print("Starting Word automation test...")

# Open Word
word, doc = open_word()

# ---------- TITLE ----------
insert_heading("Automation Test Report", 1)

insert_paragraph("This document tests various automation functions.")

set_font("Arial", 12)
# ---------- HEADER / FOOTER ----------
insert_heading("Header and Footer Example", 2)

add_header("Confidential Report")
add_footer("Generated by AI Automation")
insert_paragraph("Header and footer added successfully.")


# ---------- TEXT FORMATTING ----------
format_text(bold=True)
insert_paragraph("This line should appear bold.")

format_text(italic=True)
insert_paragraph("This line should appear italic.")

format_text(underline=True)
insert_paragraph("This line should appear underlined.")

# ---------- ALIGNMENT ----------
align_text("center")
insert_paragraph("Centered paragraph")
align_text("left")

# ---------- BULLET LIST ----------
insert_heading("Bullet List Example", 2)

insert_bullet_list([
    "Feature 1",
    "Feature 2",
    "Feature 3"
])

insert_paragraph("")  # spacing

# ---------- NUMBERED LIST ----------
insert_heading("Numbered List Example", 2)

insert_numbered_list([
    "Step 1",
    "Step 2",
    "Step 3"
])

insert_paragraph("")

# ---------- TABLE ----------
insert_heading("Table Example", 2)

table = insert_table(3,3)
insert_paragraph("")

fill_table(table, [
    ["Name", "Role", "Status"],
    ["Bhavya", "Developer", "Active"],
    ["AI Agent", "Automation", "Running"]
])
insert_paragraph("")

add_page_numbers()

# ---------- SAVE ----------
save_document(r"C:\Users\bhavy\OneDrive\Desktop\word_test.docx")

# ---------- EXPORT ----------
export_pdf(r"C:\Users\bhavy\OneDrive\Desktop\word_test.pdf")

print("All functions executed successfully.")
close_word()